### ISSUE TITLE
Bursty Sparse List (List of Lists of Blocks)

### ISSUE THREAD

**Issue by speedplane** [johnsyweb/python_sparse_list#4]
Great work on Sparse List! I want to use a Sparse List, but I'm not sure the dictionary implementation is the most efficient for me. 

### Bursty Data
My particular data is sparse, but bursty. While 95% of the indices are empty, the remaining 5% are broken up into relatively bursty chunks. Rather than store everything in a dictionary, it would be nice to store a dictionary of lists, where each list contains a range of data. This could make certain operations much more efficient.

### Use Case: Caching Result Sets
The main use case for this is caching result sets. Say I have a query that has 1M results, and I want to cache the ones I pull into a list-type structure. If I pull results 1000 at a time, there will be many contiguous blocks, and it will be much more efficient to store the data in some sort of list of lists structure.

### Implementation
Is there any chance that this will be implemented here? Would you accept a pull request that supported this type of storage?

The data structure is not conceptually difficult, but there will be a bit of hairy code for merging contiguous blocks and going from one block to the next.

**Comment by johnsyweb** [comment]
Hi @speedplane,

Thank you both for your interest and your contributions to my little project.

I'd certainly review a Pull Request that supported this type of storage.

It would be interesting to see some benchmarks around the storage and retrieval. I had a play with `benchmark` tonight and the performance is... ...not as good as I'd hoped:

```sh
[Sat 16/11/12 00:11 AEDT][s001][x86_64/darwin16.0.0/16.1.0][5.2]
<paj@librarian:~/src/python_sparse_list>
zsh 4265 [1]  (git)-[master]-% ./time_sparse_list.py             

Benchmark Report
================

Benchmark Insert
----------------

       name | rank | runs |      mean |        sd | timesBaseline
------------|------|------|-----------|-----------|--------------
       list |    1 |    5 | 8.583e-07 | 8.362e-07 |           1.0
sparse list |    2 |    5 | 4.959e-06 | 3.078e-06 | 5.77777777778

Benchmark Repr
--------------

       name | rank | runs |      mean |        sd | timesBaseline
------------|------|------|-----------|-----------|--------------
       list |    1 |    5 | 6.766e-05 | 3.687e-06 |           1.0
sparse list |    2 |    5 |  0.003041 | 0.0002311 | 44.9429175476

Benchmark Retrieval
-------------------

       name | rank | runs |      mean |        sd | timesBaseline
------------|------|------|-----------|-----------|--------------
       list |    1 |    5 | 6.199e-07 | 5.742e-07 |           1.0
sparse list |    2 |    5 | 3.529e-06 | 1.363e-06 | 5.69230769231

Each of the above 30 runs were run in random, non-consecutive order by
`benchmark` v0.1.5 (http://jspi.es/benchmark) with Python 2.7.10
Darwin-16.1.0-x86_64 on 2016-11-11 13:16:50.

```

**Comment by speedplane** [comment]
This blocky implementation will likely improve memory, and would speed up iterating. But I don't think it'll improve insertions or random access retrieval.

I was thinking that there are two ways of implementing this. One is to use arbitrary length lists that represent blocks of contiguous blocks of data. This will likely be the most efficient but it will take a bit of work to merge and break up these lists as necessary.

Another, much simpler solution may get us a good deal of the performance gains. The dictionary can point to *fixed length* lists. So, for example, if the fixed length was length 10, then index 0 in the dictionary would contain elements 0 to 9. Index 15 would contain elements 150 to 159. It's unclear what the exact performance will be, but this will have a best case performance of being 10X better (in memory and possibly iterating speed) than the current `sparse_list`.

Anyway, for better or worse, the current performance of the sparse list turned out to be suitable for me, so I'm not sure I'll have the justification to put more time into this.

**Comment by johnsyweb** [comment]
Closing this issue for now. We can reopen if the current implementation gets too slow.
